trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: 'Build and Publish'
    jobs:
      - job: Build
        displayName: 'Build and Publish Backend'
        steps:
          - checkout: self

          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '8.x' # Use your .NET version

          - script: dotnet build edusync-backend/EdySyncProject.sln --configuration $(buildConfiguration)
            displayName: 'Build Solution'

          - script: dotnet publish EdySyncProject/EdySyncProject.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
            displayName: 'Publish Project'

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: backend

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: Build
    jobs:
      - deployment: DeployBackend
        displayName: 'Deploy Backend'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: backend

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure App Service'
                  inputs:
                    azureSubscription: 'githunconnection' # Your service connection name
                    appType: 'webApp'
                    appName: 'keshavserver'      # Replace with your App Service name
                    package: '$(Pipeline.Workspace)/backend'